title: "Rodrigo Jazinski"
description: "CTO & Systems Architect | Executive Coach | Independent Researcher in Symbolic Systems"
markdown: kramdown

remote_theme: pages-themes/merlot@v0.2.0

plugins:
  - jekyll-remote-theme

show_downloads: false
